[supabase]
# 아까 수파베이스에서 복사해 둔 URL과 KEY를 여기에 넣습니다.
url = "https://rbbfzzlacelbwvhrdlvp.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYmZ6emxhY2VsYnd2aHJkbHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUwNTg3OTAsImV4cCI6MjEwMDYzNDc5MH0.JBxyv9-KV01mb5DQyBBKMBexkSLsrwO8qBexzjVEKwk"

[gemini]
# 발급받으신 구글 제미나이 API 키를 여기에 넣습니다.
api_key = "AQ.Ab8RN6IJb8ZecK8h6XI6N92gLP_wj6K8hQ8wv2jO9AMZZXvkTA"
